add boolean, date & timestamp partition types
delta-io/delta-rs pull request #1180
Opened 2023-02-26 15:53 UTC by marijncv

# Description
Adds boolean, date & timestamp partition value types

# Related Issue(s)
contributes to #1170

2023-03-01 03:20 UTC, wjones127 requested changes
Thanks for working on this @marijncv!

Just one comment, but otherwise looks great.

2023-03-01 03:20 UTC, wjones127 commented on rust/src/writer/utils.rs
> +            (Arc::new(Int8Array::from(vec![None, Some(2)])), None),
I think we technically don't care to test the behavior that we only use the first value; it's possible a future version of this function will error if not all values are identical. Could you change each case to just have a array 1 value long?
```suggestion
            (Arc::new(Int8Array::from(vec![None])), None),
```

2023-03-03 07:36 UTC, fvaleye approved these changes
LGTM

2023-03-06 04:17 UTC, wjones127 requested changes
Sorry for the delay. I meant my earlier comment about not needing more than 1 value in the test to apply to all the test cases, not just the one I had made a suggestion on.

Added a few other comments to make the test cases a little more compact.

2023-03-06 04:17 UTC, wjones127 commented on rust/src/writer/utils.rs
> +            ),
```suggestion
            (Arc::new(Int8Array::from(vec![1])), Some("1")),
            (Arc::new(Int16Array::from(vec![1])), Some("1")),
            (Arc::new(Int32Array::from(vec![1])), Some("1")),
```

2023-03-06 04:17 UTC, wjones127 commented on rust/src/writer/utils.rs
> +        let reference_pairs: Vec<(Arc<dyn Array>, Option<String>)> = vec![
```suggestion
        let reference_pairs: Vec<(Arc<dyn Array>, Option<&str>)> = vec![
```

2023-03-06 04:17 UTC, wjones127 commented on rust/src/writer/utils.rs
> +            assert_eq!(stringified_partition_value(&vals).unwrap(), result)
You can use `as_deref()` to turn `Option<String>` into `Option<&str>`:
```suggestion
            assert_eq!(
                stringified_partition_value(&vals).unwrap().as_deref(),
                result
            )
```

2023-03-06 04:17 UTC, wjones127 commented on rust/src/writer/utils.rs
> +            ),
The `StringArray::from` implementation can take a `&str`:

```suggestion
            (Arc::new(StringArray::from(vec!["1"])), Some("1")),
```

2023-03-06 11:53 UTC, roeap approved these changes
LGTM!

2023-03-06 15:53 UTC, wjones127 approved these changes
Great! Thanks @marijncv

2023-03-06 15:53 UTC, merged