Fix names and nullability when creating RecordBatch from MapArray
delta-io/delta-rs pull request #1258
Opened 2023-04-03 01:39 UTC by balbok0

# Description
When creating a RecordBatch with one of the columns being a MapArray, there are issues with naming of sub-columns, as well as nullability of the "elements/key_value" sub-column.

# Related Issue(s)

- closes #1257

# Documentation

See https://www.rustexplorer.com/b/o7bfm4 for a breaking example.
I initially thought that the issue is specifically for array with 0-length maps, but `nullable` mismatch happens even when all of the map elements have values.

2023-04-03 19:59 UTC, rtyler commented
Thanks for the pull request! @balbok0 would you be able to take your failing example and turn that into a unit or integration test so we don't have this regression in the future?

2023-04-03 21:57 UTC, wjones127 commented
I’d like for us to fix this, but I also hope we can find a way to simultaneously support older PyArrow versions in the Python bindings.

2023-04-04 05:55 UTC, balbok0 commented
@wjones127 are there some specific pyarrow versions you have in mind? I wasn't able to find a specific arrow-cpp/pyarrow version that changed the naming scheme.

2023-04-05 00:28 UTC, balbok0 commented
Added failing example as a test.

2023-04-08 03:46 UTC, wjones127 requested changes
This generally looks good. I was worried about PyArrow and other languages because the Arrow standard specifies field names as "key" not "keys" and "value" not "values" (arrow-rs deviates from this). But the PyArrow C Data Interface import actually ignores these field names on map types anyways, so it shouldn't matter that they are different. So we can ignore that worry.

I have a few small nits on the tests, but otherwise looks good to go.

2023-04-08 03:46 UTC, wjones127 commented on rust/src/delta_arrow.rs
> +            <crate::SchemaDataType as TryFrom<&ArrowDataType>>::try_from(&timestamp_field).unwrap(),
```suggestion
        );
        let converted_map: crate::SchemaDataType = (&timestamp_field).try_into().unwrap();
        assert_eq!(
            converted_map,
```

2023-04-08 03:47 UTC, wjones127 commented
Oh and could you rebase? We just fixed some of the deprecation warnings.

2023-04-09 22:19 UTC, balbok0 commented
Thanks for comments! I applied changes and rebased. Lmk if there is anything else that needs to done before merge.

2023-04-09 22:23 UTC, wjones127 approved these changes

2023-04-09 22:34 UTC, merged