Readme
delta-io/delta-rs pull request #1440
Opened 2023-06-05 19:36 UTC by roeap

# Description

With summit coming up I thought we might update our README, since delta-rs has evolved quite a bit since the README was first written...

Just opening the Draft to get feedback on the general "patterns" i.e. how the tables are formatted, how detailed we want to show the features and mostly the looks of the header.

Also hoping our community experts may have some content they wat to add here 😆.

cc @dennyglee @MrPowers @wjones127 @rtyler @houqp @fvaleye

2023-06-06 03:37 UTC, wjones127 reviewed
This is looking better. I had a few suggestions

2023-06-06 03:37 UTC, wjones127 commented on README.md
> +The same table written cal also be loaded using the core rust crate.
```suggestion
The same table written can also be loaded using the core Rust crate:
```

2023-06-06 03:37 UTC, wjones127 commented on README.md
> +[done]: https://cdn.jsdelivr.net/gh/Readme-Workflows/Readme-Icons@main/icons/octicons/IssueClosed.svg
Fancy!

2023-06-06 03:37 UTC, wjones127 commented on python/pyproject.toml
> +    "Development Status :: 4 - Beta",
👍

2023-06-06 03:37 UTC, wjones127 commented on README.md
What do you think of adding a "Powered By" section and listing Apache Arrow and DataFusion?

2023-06-06 03:37 UTC, wjones127 commented on REA_DME.adoc
Are we to delete this?

2023-06-06 03:37 UTC, wjones127 commented on README.md
> +  </a>
Could we add back a "Get involved section"?

Could list:

* Join the slack workspace (the button is nice, but it's kind of small)
* Report an issue
* Looking to contribute? See our list of good first issues (https://github.com/delta-io/delta-rs/contribute)

2023-06-06 05:02 UTC, dennyglee requested changes
This is really nice, thanks for tackling this.  Minor suggestions noted.

2023-06-06 05:02 UTC, dennyglee commented on README.md
> +| S3 - AWS             |        ![done]        |        ![done]        | requires lock for concurrent writes |
Should we point to the docs to explain how to spin up DynamoDB for the lock?

2023-06-06 05:02 UTC, dennyglee commented on README.md
> +[done]: https://cdn.jsdelivr.net/gh/Readme-Workflows/Readme-Icons@main/icons/octicons/IssueClosed.svg
Seriously awesome :)

2023-06-06 05:03 UTC, dennyglee commented on README.md
> +The delta-rs project aims to unlock the power of the Deltalake for as many users and projects as possible
Please update to "Delta Lake"

2023-06-06 05:03 UTC, dennyglee commented on README.md
> +API that lets you query, inspect, and operate your Deltalake with ease.
Please update to "Delta Lake"

2023-06-06 05:04 UTC, dennyglee commented on README.md
> +The deltalake library aim to adopt familiar patterns from other libraries in data processing,
Suggest either "The Delta Lake library aims to..." or "The `deltalake` library aims to..."

2023-06-06 05:32 UTC, roeap commented on README.md
should we then also submit a PR to the official arrow "pwered_by" section? 

https://arrow.apache.org/powered_by/

2023-06-06 06:28 UTC, roeap commented on REA_DME.adoc
we are :) - just keeping it around for refence, until all content is ported over..

2023-06-06 21:07 UTC, MrPowers commented
Looks like some great improvements!

2023-06-07 00:26 UTC, wjones127 commented on README.md
> +- [Join us in our slack worksapce](https://go.delta.io/slack)
```suggestion
- [Join us in our Slack workspace](https://go.delta.io/slack)
```

2023-06-07 00:27 UTC, wjones127 reviewed
on typo

2023-06-16 11:46 UTC, MrPowers commented on README.md
> +| Version 2      | Column Invatiants                             |       ![done]        |
Little typo here (Invatiants => Invariants)

2023-07-15 05:12 UTC, rtyler commented on README.md
> +| Version 2      | Column Invatiants                             |       ![done]        |
```suggestion
| Version 2      | Column Invariants                             |       ![done]        |
```

2023-07-15 05:13 UTC, rtyler submitted a review, later dismissed

2023-09-15 04:46 UTC, rtyler approved these changes

2023-09-15 05:07 UTC, merged