Add a simple error message for NotATable
delta-io/delta-rs pull request #286
Opened 2021-06-10 17:36 UTC by rtyler

# Description

This commit updates NotATable to provide some more useful user-facing error
information.

# Related Issue(s)

* #267

2021-06-10 17:37 UTC, houqp submitted a review, later dismissed

2021-06-10 17:37 UTC, houqp commented on rust/src/delta.rs
> +                                return Err(DeltaTableError::NotATable("No snapshot  or version 0 found, perhaps this is an empty directory?".to_string()));
```suggestion
                                return Err(DeltaTableError::NotATable("No snapshot or version 0 found, perhaps this is an empty directory?".to_string()));
```

2021-06-10 18:44 UTC, nfx commented on rust/src/delta.rs
> +                                return Err(DeltaTableError::NotATable("No snapshot  or version 0 found, perhaps this is an empty directory?".to_string()));
@houqp you've missed `{0}`

2021-06-10 18:49 UTC, nfx requested changes
What

2021-06-13 17:19 UTC, houqp submitted a review, later dismissed

2021-06-13 18:06 UTC, houqp approved these changes

2021-06-13 18:07 UTC, merged