feat: support reading tables via Unity Catalog provided credentials
delta-io/delta-rs pull request #3078
Opened 2024-12-22 17:39 UTC by hntd187

# Description
You can read tables via UC provided creds.

# Related Issue(s)

# Documentation
[Temp Creds API](https://docs.databricks.com/api/workspace/temporarytablecredentials/generatetemporarytablecredentials)

2025-01-12 16:29 UTC, roeap reviewed
Just some minor nits to maybe look at?

One question. Do i read that right, that we are only supporting AWS for now?

2025-01-12 16:29 UTC, roeap commented on crates/catalog-unity/src/datafusion.rs
> +            .max_capacity(1000)
Probably won't hurt us, as credentials are not large, but 1000 seems like a lot for a single client?

2025-01-12 16:29 UTC, roeap commented on crates/catalog-unity/src/datafusion.rs
> +        tracing::info!(
Does debug suffice here?

2025-01-12 16:29 UTC, roeap commented on crates/catalog-unity/src/datafusion.rs
> +                let new_storage_opts = temp_creds.aws_temp_credentials.unwrap().into();
Missed unwrap? If its safe, maybe levae a comment?

2025-01-12 16:29 UTC, roeap commented on crates/catalog-unity/src/lib.rs
> +                    tracing::info!("Found relevant env: {}", key);
Debug?

2025-01-17 08:43 UTC, roeap commented
the build failures should hopefully be addressed by #3138 - could you merge / rebase?

2025-01-19 10:53 UTC, ion-elgreco commented on crates/catalog-unity/Cargo.toml
> +default = ["datafusion", "aws"]
Why is the default AWS?

2025-01-19 10:54 UTC, ion-elgreco commented on crates/catalog-unity/Cargo.toml
> +aws = ["deltalake-aws"]
Maybe we should call this just `s3`

2025-01-19 11:20 UTC, ion-elgreco requested changes
Looks good, just some small nits. Also I suggest we add an integration test to the CI, this would also help with setting up python tests later on

2025-01-19 11:20 UTC, ion-elgreco commented on crates/catalog-unity/src/datafusion.rs
> +        name: &str,
```suggestion
        table: &str,
```
?

2025-01-19 11:20 UTC, ion-elgreco commented on crates/catalog-unity/src/models.rs
> +        None
Won't this give unexpected results when you forgot to set the Azure feature? Maybe better to gracefully error when see azure/aws/gcp credentials but the feature was not set.

2025-01-19 17:09 UTC, hntd187 commented on crates/catalog-unity/Cargo.toml
> +aws = ["deltalake-aws"]
it's named to coincide with the crate names

2025-01-19 17:29 UTC, ion-elgreco commented on crates/catalog-unity/Cargo.toml
> +aws = ["deltalake-aws"]
But then I would remove the r2 feature

2025-01-20 07:32 UTC, ion-elgreco commented on crates/catalog-unity/src/lib.rs
> +        dbg!(&get_table_response);
Left a dbg! in there : )

2025-01-20 18:01 UTC, ion-elgreco approved these changes
Great work! :D

2025-01-20 19:13 UTC, merged

2025-01-21 15:49 UTC, omkar-foss commented
> Great work! :D

+1 Lovely PR @hntd187, I'll start using the temp creds function in PR https://github.com/delta-io/delta-rs/pull/3113. Thanks! 😁