Use `tokio::fs::rename` in `put_obj`.
delta-io/delta-rs pull request #403
Opened 2021-08-21 02:05 UTC by zijie0

# Description

As a follow up of #367 , use syscall rename in `put_obj` to avoid race conditions.

# Related Issue(s)

- related to #361

2021-08-21 04:30 UTC, houqp reviewed
I think the swap argument we added to the atomic_rename method is not needed anymore right?

2021-08-21 04:31 UTC, mosyp submitted a review, later dismissed

2021-08-21 04:32 UTC, mosyp commented
> I think the swap argument we added to the atomic_rename method is not needed anymore right?

Feels like it, that was the only usage

2021-08-21 06:50 UTC, zijie0 commented
@houqp @mosyp Do you think that we can also remove the swap argument in this PR? If so, I can help with the change.

2021-08-21 07:31 UTC, houqp commented
@zijie0 yes, let's do that :)

2021-08-23 08:29 UTC, zijie0 commented
I also refactor the method name to `rename_if_not_exists`. If there's any problems, please let me know.

2021-08-23 10:36 UTC, mosyp commented
Tbh, not a fan of `rename_if_not_exists` naming, as it differs to the API we're calling, and it's basically a wrapping call. But that's just imho. @houqp wdyt?

2021-08-23 10:38 UTC, mosyp approved these changes
other than that, lgtm

2021-08-23 11:50 UTC, zijie0 commented
Maybe `rename_noreplace` could be another option? :)

2021-08-24 05:59 UTC, houqp commented
`rename_noreplace` works for me :) I don't have a strong opinion on the naming as long as it differentiates from just `rename`, which is ambigous and could mean replace or no replace.

@mosyp when you said `as it differs to the API we're calling`, are you referring to `StorageBackend::rename`? If so, I think we should change the trait and rename that method to a more explicit name as well.

2021-08-24 10:32 UTC, mosyp requested changes
Okay, having another thoughts on that, this is going to be a breaking change. No replace behavior will not work with `_last_checkpoint` file. As it's rewritten on each new checkpoint. 
Moreover, s3 backend is always replace. I discourage having different behavior for the same API function. 

There's no test failing as main is not having the latest arrow changes, that are required for checkpoints to fully work. But this branch does https://github.com/delta-io/delta-rs/tree/writer-map-support. There's test case which rewrites `_last_checkpoint` that should fails with changes in this PR

2021-08-24 11:02 UTC, zijie0 commented
@mosyp I think `tokio::fs::rename` which is used in `put_obj` should support overwrite by default?

2021-08-24 11:11 UTC, mosyp approved these changes
@zijie0 Ah you're right, got confused on my coffee-less morning. Looking good then, I've just found that we have a test for this behavior https://github.com/delta-io/delta-rs/blob/main/rust/src/storage/file/mod.rs#L145

2021-08-24 11:11 UTC, merged

2021-08-24 11:11 UTC, mosyp commented
@zijie0 thank you!

2021-08-24 15:51 UTC, houqp commented
Thank you @zijie0 and thank you @mosyp for the detailed review!