WIP: Add authorization options for azure storage backend
delta-io/delta-rs pull request #486
Opened 2021-11-01 10:34 UTC by roeap

# Description

This PR extends the available options to authorize the azure storage backend against a storage account.

- add `AZURE_STORAGE_CONNECTION_STRING`
- Fall back on `DefaultCredential` if no other option is available
- `AZURE_STORAGE_ACCOUNT` is still required for all bur connection string.
- use latest azure crates

additinally the test setup for the azure storage backend is extended

- add `setup_azurite.sh` and extend docker-compose file to run azurite container
- add an `azure_test` step mimicking the `s3_test` step to build config
- copy over read-related tests from s3_tests

The handling of the container client, specifically handling client updates on token expiry is heavily inspired by how the rusoto crate managed credentials internally. 

# Related Issue(s)

- closes #149
- closes #255

the somewhat awkward implementation in `list_objs` may be related to Azure/azure-sdk-for-rust#377, but I lack expereince with the lifetime handling in rust, so I may just have missed something trivial.

# Documentation

2021-11-01 11:52 UTC, roeap commented
@houqp , @fvaleye I tried implementing more storage options which turned out to be a bit more involved then expected. Since this includes many thins fairly new to be - especially in the rust world - I'd be very happy to get some feedback if this is going in the right direction. Specifically when it comes to handling the refresh of the container client.

2021-11-02 06:32 UTC, houqp commented
@roeap I am not very familiar with azure sdk, so I will need bit more time to read through the code this weekend.

2021-11-05 04:09 UTC, houqp commented
cc @thovoll since he is the expert of Azure rust binding :)

2021-11-12 01:32 UTC, thovoll commented
@roeap please update PR description based on removing Azurite, thanks!

2021-11-12 01:34 UTC, thovoll commented
@roeap to what degree can we use the [current testing approach](https://github.com/delta-io/delta-rs/blob/222837cf8f5e09379472ce2ad1c5db0d5bc8a9b6/rust/tests/azure_test.rs#L16) for this new code?

2021-11-12 01:36 UTC, thovoll commented on build/setup_azurite.sh
> +#!/bin/bash
Do we still need this file?

2021-11-12 01:37 UTC, thovoll commented on docker-compose.yml
> +      - "./rust/tests/data/concurrent_workers:/data/concurrent_workers"
Remove Azurite stuff?

2021-11-12 01:39 UTC, thovoll requested changes
Looks good overall, thanks for tackling this! I'd like to see the remaining Azurite code removed and the existing test modified.

2021-11-12 07:59 UTC, roeap commented on build/setup_azurite.sh
> +#!/bin/bash
done

2021-11-12 07:59 UTC, roeap commented on docker-compose.yml
> +      - "./rust/tests/data/concurrent_workers:/data/concurrent_workers"
done

2021-11-12 08:05 UTC, roeap commented
I removed the azurite testing code and had a look into how tests are currently done. To me it seems that the account being used may actually not even exist any more. As is the test is ignored, and when trying to ruin it, I get dns not found. Maybe @rtyler can tell us if that account still exists, and if so, if it should still be used.

Beyond that there are some challenges left to actually test the core of this PR. The "static" authorization schemes are actually quite similar. However the most interesting part - authenticating with a service principal - would not be tested. What I can say is that it worked locally using a work account, but that does not help much ... @thovoll any ideas how to test this scenario as well?

2021-11-12 14:00 UTC, thovoll commented
Thanks @roeap. Ultimately, an approach like the mock testing framework that is being used by the Azure Rust SDK would make sense for integration tests. Until then we are stuck with e2e testing using real Azure resources. 

I found the same DNS issue when running the ignored test last night and pinged @rtyler as well, but instead of resurrecting this, I propose we use the same approach that is used in the Azure Rust SDK where the (e2e) tests have to be run manually by developers on their local machine, using their own Azure resources (requires setting env variables to make the various auth schemes work). In CI, the integration tests are just `cargo check`ed (the integration tests using the mock testing framework are actually executed in CI). PR submitters would have to attest to the fact that they ran the e2e tests locally, like you did above. This is not ideal, but a incremental improvement nonetheless.

2021-11-12 14:01 UTC, thovoll commented
BTW, similar issues are being discussed over in the Azure Rust SDK [here](https://github.com/Azure/azure-sdk-for-rust/issues/428#issuecomment-965881344).

2021-11-12 14:05 UTC, thovoll commented
@roeap please also update the PR description to remove the Azurite references. Thanks!

2021-11-15 05:07 UTC, houqp commented
The change looks good to me overall, agree with @thovoll on testing :)

2021-11-15 15:04 UTC, roeap commented
Thanks for the feedback. Just for me to understand, in terms of testing to idea would now be to mirgate some of the S3 tests, mark them with ignored, and maybe write a few sentences for devs to understand how to do e2e testing locally. In subsequent PRs we would then gradually improve testing to eventually have it run in CI - ideally using the pipelines architecture from the azure sdk repo? @thovoll @houqp

2021-11-15 15:23 UTC, thovoll commented
I think we would leave the S3 tests alone, since they can work with the localstack emulator.

The [Azure test](https://github.com/delta-io/delta-rs/blob/main/rust/tests/azure_test.rs) would be run locally using your own Azure Storage account, I think you have already done this correct?

If you're up for it as part of this PR, you could [modify this to not hard code those 3 values](https://github.com/delta-io/delta-rs/blob/c5571706e09b97499f5f3546cdea2a2c650b4d40/rust/tests/azure_test.rs#L12-L16) and document how to run this test locally (something light, just saying that "the following 3 env variables have to be set").

2021-11-15 15:25 UTC, thovoll commented
And yes, if we have consensus we can eventually add a mock testing framework for the Azure tests so we can run them in CI without needing an emulator or real Azure resources.

2021-11-15 16:43 UTC, roeap commented
@thovoll @houqp - i updated the azure_test file and included a description how to setup and execute tests locally.

2021-11-15 17:41 UTC, thovoll commented
Thanks @roeap, looks good! I think this is good to merge. @houqp

2021-11-16 06:41 UTC, houqp commented
awesome, @roeap do you mind resolving the conflicts in Cargo.lock so we can merge it?

2021-11-16 06:58 UTC, roeap commented
Thanks @houqp @thovoll for your support/reviews. The conflicts should be resolved now.

2021-11-16 07:24 UTC, houqp approved these changes
LGTM

2021-11-16 07:26 UTC, merged

2021-11-16 07:28 UTC, houqp commented
Thank you @roeap for the hard work and @thovoll for the review!