Update schema.rs for metadata json parsing after changes
delta-io/delta-rs pull request #532
Opened 2022-01-04 18:01 UTC by d-bhutada

# Description
The description of the main changes of your pull request

# Related Issue(s)

# Documentation

2022-01-05 11:22 UTC, langelgjm requested changes

2022-01-05 11:22 UTC, langelgjm commented on rust/src/schema.rs
> +use serde_json::Value
@d-bhutada this line needs a semicolon at the end.

2022-01-05 11:23 UTC, langelgjm commented
This PR is the same as #531 which builds locally for me.

2022-01-05 14:03 UTC, langelgjm commented
I can confirm that this resolves #457 and #524 for me.

2022-01-06 00:58 UTC, houqp commented
thanks @d-bhutada , closing this since #531 landed first ;)

2022-01-06 00:58 UTC, closed without merging