Added without_files flag to DeltaTable constructor
delta-io/delta-rs pull request #866
Opened 2022-10-07 12:23 UTC by MykhailoHevak

# Description
Added _without_files_ flag to DeltaTable constructor. If the flag is set it will be called method _without_files_ in the **DeltaTableBuilder**. And this allows users to control memory usage. Some append-only applications might have no need of tracking any files.

# Documentation
Indicates whether DeltaTable should track files. This defaults to "true". Some append-only applications might have no need of tracking any files. Hence, DeltaTable will be loaded with significant memory reduction.

2022-10-07 15:26 UTC, wjones127 requested changes
What's the behavior of `DeltaTable.file_uris()` when `without_files=True`? Does it return empty? Or raise an error? Or load the files? We might want to add a unit test for that in Python.

2022-10-07 15:26 UTC, wjones127 commented on python/deltalake/table.py
>          """
Will want to document this parameter:

```suggestion
        :param without_files: If True, will load table without tracking files. Some 
          append-only applications might have no need of tracking any files. So, the
          DeltaTable will be loaded with a significant memory reduction.
        """
```

2022-10-07 15:26 UTC, wjones127 commented on python/deltalake/table.py
> +        without_files: Optional[bool] = None
Why not make it clear what the default is in the signature?

```suggestion
        without_files: bool = False
```

2022-10-08 17:54 UTC, wjones127 commented
> What's the behavior of DeltaTable.file_uris() when without_files=True? Does it return empty? Or raise an error? Or load the files? We might want to add a unit test for that in Python.

Just checked and it returns an empty list. We should document that for now, and consider changing that behavior in the future (#867).

2022-10-10 17:12 UTC, wjones127 commented
@MykhailoHevak looks like the merge you pushed overwrote the changes you accepted in the GitHub UI. Could you add those back?

2022-10-10 17:50 UTC, MykhailoHevak commented
> @MykhailoHevak looks like the merge you pushed overwrote the changes you accepted in the GitHub UI. Could you add those back?

Oooops... I did it accidentally. Is it OK now?

2022-10-13 15:46 UTC, MykhailoHevak commented
Do I have to do something else?

2022-10-13 17:22 UTC, wjones127 commented on python/src/lib.rs
> +        without_files: bool
```suggestion
        without_files: bool,
```

2022-10-13 20:06 UTC, wjones127 approved these changes

2022-10-13 20:06 UTC, merged

2022-10-13 20:07 UTC, wjones127 commented
Thanks @MykhailoHevak!

2022-11-09 15:23 UTC, dennyglee commented
Hey @MykhailoHevak I believe this is your first PR to the delta repo.  Can you ping me (dennyglee) via the [Delta Users slack](https://go.delta.io/slack) so we can send you some swag?  Thanks!